modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Biome%20Spawn%20Point"
logoFile="icon.png"

[[mods]]
modId="biomespawnpoint"
version="2.2"
displayName="Biome Spawn Point"
displayURL="https://serilum.com/mod/biome-spawn-point"
authors="Rick South"
description='''Allows specifying which biome players will spawn in on new world creation.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.biomespawnpoint]]
    modId="collective"
    type="required"
    versionRange="[7.53,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.biomespawnpoint]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "biomespawnpoint.mixins.json"